### PR TITLE
GitHub Icons

### PR DESCRIPTION
**Pull request by simongamester**
Replaced twitter with GitHub icon in header
Added GitHub icon to footer.
Fixed JSON page edit buttons

### CODE REVIEW

**Comment by PhilBarrett** [comment]
@simongamester I can see the changes on the GH pages, but to have seamless on the wordpress too. Are you able to help with this too please?



screen shot 2017-06-29 at 20 50 34

screen shot 2017-06-29 at 20 52 18

**Comment by simongamester** [comment]
Yes, will fix this shortly...

**Comment by tony-shannon** [comment]
thanks

**Comment by simongamester** [comment]
This is now live.

Simon Gamester
Root Solutions

m.  07793 274937
e. simon@rootsol.co.uk <mailto:simon@rootsol.co.uk>
 <mailto:simon@rootsol.com>w. http://www.rootsol.co.uk <http://www.rootsol.com/>
skype. rootsol
twitter. @rootsol <http://twitter.com/#!/rootsol>

**Comment by tony-shannon** [comment]
many thanks
T

**Pull request merged**
